[openai]
# OpenAI API Configuration for text generation
chat_model = "gpt-4o"
max_tokens = 1000
temperature = 0.7

[together_ai]
# Together AI Configuration for image generation
image_model = "black-forest-labs/FLUX.1-schnell"
max_tokens = 512
temperature = 0.7

[interface]
# Interface Configuration
max_pdf_files = 10
description = "Create expert witness personas from legal case content. Upload up to 10 PDF files and/or enter text descriptions." 