[openai]
# OpenAI API Configuration
chat_model = "gpt-4o"
image_model = "dall-e-3"
max_tokens = 1500
temperature = 0.7

[image_generation]
# DALL-E 3 Generation Settings
size = "1024x1024"
quality = "standard"  # standard, hd
n = 1 