[openai]
# OpenAI API Configuration
chat_model = "gpt-4o"
image_model = "gpt-image-1"
max_tokens = 1500
temperature = 0.7

[image_generation]
# GPT Image 1 Generation Settings
size = "1024x1024"
quality = "auto"  # auto, low, medium, high
output_format = "jpeg"  # jpeg, png, webp 